# Generated by Django 4.1.9 on 2023-07-08 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.FileField(upload_to='')),
                ('nom', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id_match', models.IntegerField(primary_key=True, serialize=False)),
                ('gagnant', models.BooleanField(null=True)),
                ('champion1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion1', to='game.champion')),
                ('champion2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion2', to='game.champion')),
            ],
        ),
    ]
