# Generated by Django 4.1.9 on 2023-07-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='id_match',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
