# Generated by Django 4.1.9 on 2023-07-08 08:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_rename_titre_champions_nom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Champions',
            new_name='Champion',
        ),
    ]
