# Generated by Django 4.2.3 on 2023-07-10 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_match_date_match_dump_match_score1_match_score2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='code',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'c', 'ml'])]),
        ),
    ]
