# Generated by Django 4.2.3 on 2023-07-12 10:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_champion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='code',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'c', 'ml', 'cpp', 'cc', 'zip', 'tgz', 'tar.gz'])]),
        ),
    ]
