# Generated by Django 4.2.3 on 2023-07-12 09:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0004_alter_champion_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='code',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'c', 'ml', 'cpp', 'cc', 'zip', 'tgz', 'tar.gz'])]),
        ),
        migrations.AlterField(
            model_name='champion',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='champion1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='champion1', to='game.champion'),
        ),
        migrations.AlterField(
            model_name='match',
            name='champion2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='champion2', to='game.champion'),
        ),
        migrations.AlterField(
            model_name='match',
            name='dump',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])]),
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)]),
        ),
    ]
