# Generated by Django 4.2.3 on 2023-07-12 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_champion_code'),
        ('game', '0005_alter_champion_code_alter_champion_uploader_and_more'),
    ]

    operations = [
    ]
