# Generated by Django 4.2.3 on 2023-07-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_champion_code_alter_champion_uploader_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='nom',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
