# Generated by Django 4.2.3 on 2023-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_merge_20230712_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='compilation_status',
            field=models.CharField(choices=[('EA', 'En Attente'), ('EC', 'En Cours'), ('FI', 'Fini'), ('ER', 'Erreur')], default='ER', editable=False, max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('EA', 'En Attente'), ('EC', 'En Cours'), ('FI', 'Fini'), ('ER', 'Erreur')], editable=False, max_length=5),
        ),
    ]
