# Generated by Django 4.2.3 on 2023-07-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_champion_compilation_status_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='compilation_status',
            field=models.CharField(choices=[('EA', 'En Attente'), ('EC', 'En Cours'), ('FI', 'Fini'), ('ER', 'Erreur')], default='EA', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('EA', 'En Attente'), ('EC', 'En Cours'), ('FI', 'Fini'), ('ER', 'Erreur')], default='EA', editable=False, max_length=5),
        ),
    ]
