# Generated by Django 4.2.3 on 2023-07-12 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_champion_nom'),
        ('game', '0008_alter_champion_compilation_status_alter_match_status'),
    ]

    operations = [
    ]
