# Generated by Django 4.2.3 on 2023-07-13 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_merge_20230712_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='gagnant',
            field=models.IntegerField(choices=[(1, 'Champion 1'), (2, 'Champion 2'), (-1, 'Non Fini'), (0, 'Egalite')], default=-1, editable=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)]),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(blank=True, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(21)]),
        ),
    ]
