# Generated by Django 4.2.3 on 2023-07-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('game', '0010_alter_match_gagnant_alter_match_score1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='compile_task',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_q.task'),
        ),
    ]
