# Generated by Django 4.2.3 on 2023-07-14 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('game', '0011_champion_compile_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='compile_task',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_q.task'),
        ),
    ]
