# Generated by Django 4.2.3 on 2023-07-16 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('game', '0013_remove_match_dump'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_task',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='django_q.task'),
        ),
    ]
