# Generated by Django 4.2.3 on 2023-07-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_match_match_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='supprimer',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
