# Generated by Django 4.2.3 on 2023-07-20 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_alter_champion_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='nom',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z-_0-9]*$', 'Les seuls caractères valides sont les lettres, les chiffres, - et _.')]),
        ),
    ]
