# Generated by Django 4.2.3 on 2023-07-21 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_alter_champion_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='code',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip', 'tgz', 'tar.gz'])]),
        ),
    ]
