# Generated by Django 4.2.3 on 2023-07-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_alter_champion_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id_tournoi', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('EA', 'En Attente'), ('EC', 'En Cours'), ('FI', 'Fini'), ('ER', 'Erreur'), ('LP', 'Lancement Programme')], default='EA', max_length=2)),
                ('max_champions', models.IntegerField(default=3)),
                ('date_lancement', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('EA', 'En Attente'), ('EC', 'En Cours'), ('FI', 'Fini'), ('ER', 'Erreur')], default='EA', editable=False, max_length=2),
        ),
        migrations.CreateModel(
            name='Inscrit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classement', models.IntegerField(null=True)),
                ('nb_points', models.IntegerField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.champion')),
                ('tournoi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.tournoi')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournoi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.tournoi'),
        ),
        migrations.AddConstraint(
            model_name='inscrit',
            constraint=models.UniqueConstraint(fields=('tournoi', 'champion'), name='champion unique dans un tournoi'),
        ),
    ]
