# Generated by Django 4.2.3 on 2023-07-29 20:31

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_tournoi_alter_match_status_inscrit_match_tournoi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='date_lancement',
            field=models.DateTimeField(validators=[game.models.Tournoi.valide_date]),
        ),
        migrations.AlterField(
            model_name='tournoi',
            name='status',
            field=models.CharField(choices=[('EA', 'En Attente'), ('EC', 'En Cours'), ('FI', 'Fini'), ('ER', 'Erreur'), ('LP', 'Lancement Programmé')], default='EA', max_length=2),
        ),
    ]
