# Generated by Django 4.2.3 on 2023-07-30 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_alter_tournoi_date_lancement'),
        ('game', '0021_alter_tournoi_date_lancement_alter_tournoi_status'),
    ]

    operations = [
    ]
