# Generated by Django 4.2.3 on 2023-07-30 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_alter_match_tournoi'),
        ('game', '0022_merge_20230730_1405'),
    ]

    operations = [
    ]
