# Generated by Django 4.2.3 on 2023-07-30 14:38

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_merge_20230730_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='date_lancement',
            field=models.DateTimeField(blank=True, null=True, validators=[game.models.Tournoi.valide_date]),
        ),
    ]
