# Generated by Django 4.2.3 on 2023-07-31 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('game', '0026_alter_tournoi_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournoi',
            name='schedule',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.schedule'),
        ),
    ]
