# Generated by Django 4.2.3 on 2023-07-31 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0014_schedule_cluster'),
        ('game', '0027_alter_tournoi_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='champion',
            name='compile_task',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.task'),
        ),
        migrations.AlterField(
            model_name='match',
            name='match_task',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_q.task'),
        ),
    ]
