# Generated by Django 4.2.3 on 2023-07-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_alter_champion_compile_task_alter_match_match_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='nb_matchs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournoi',
            name='nb_matchs_done',
            field=models.IntegerField(default=0),
        ),
    ]
