# Generated by Django 4.2.3 on 2023-08-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_tournoi_nb_matchs_tournoi_nb_matchs_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournoi',
            name='nb_matchs',
        ),
        migrations.RemoveField(
            model_name='tournoi',
            name='nb_matchs_done',
        ),
        migrations.AddField(
            model_name='inscrit',
            name='defaites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='egalites',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='victoires',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='classement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inscrit',
            name='nb_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
