# Generated by Django 4.2.3 on 2023-08-03 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_remove_tournoi_nb_matchs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='lanceur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='game.champion'),
        ),
    ]
