# Generated by Django 4.2.3 on 2023-08-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_alter_match_lanceur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='champion1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion1', to='game.champion'),
        ),
        migrations.AlterField(
            model_name='match',
            name='champion2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champion2', to='game.champion'),
        ),
    ]
