# Generated by Django 4.2.3 on 2023-08-05 08:26

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_alter_match_champion1_alter_match_champion2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournoi',
            name='nb_matchs',
            field=models.IntegerField(default=10, validators=[game.models.even]),
        ),
    ]
