# Generated by Django 4.2.3 on 2023-08-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0035_champion_game_champi_date_b0fac9_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='fin_prematuree',
            field=models.BooleanField(default=False),
        ),
    ]
