# Generated by Django 4.2.3 on 2023-08-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_match_fin_prematuree'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['fin_prematuree', 'tournoi', '-date'], name='game_match_fin_pre_3ae1a9_idx'),
        ),
    ]
